---

- name: Fail if systemd_restart_mode is invalid
  ansible.builtin.fail:
    msg: >-
      Invalid value: `{{ systemd_restart_mode }}`
  when: "systemd_restart_mode not in ['clean-stop-start', 'one-by-one']"
